version: "3.7"
services:

  nginx4static:
    image: nginx
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.nginx4static.rule=Host(`haga.tibillet.fr`)
      - traefik.http.routers.nginx4static.tls.certresolver=tlsresolver

    ports:
      - 8012:80
    networks:
      - frontend

networks:
  frontend:
    external: true


